[workspace]
members = [
  "programs/ura_chaos_arena"
]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
anchor-lang = "0.29.0"

[profile.release]
opt-level = "s"

[profile.dev]
opt-level = 1
