[package]
name = "ura_chaos_arena"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "ura_chaos_arena"

[dependencies]
anchor-lang = { workspace = true }
pyth-sdk-solana = "0.8"
